// renderers/lit/src/0.8/ui/text.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {markdown} from './directives/directives.js';
import {Root} from './root.js';
import {A2uiMessageProcessor} from '@a2ui/web_core/data/model-processor';
import * as Primitives from '@a2ui/web_core/types/primitives';
import * as Types from '@a2ui/web_core/types/types';
import * as Context from './context/context.js';
import {consume} from '@lit/context';
import {classMap} from 'lit/directives/class-map.js';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';
import {Styles} from '../index.js';

interface HintedStyles {
  h1: Record<string, string>;
  h2: Record<string, string>;
  h3: Record<string, string>;
  h4: Record<string, string>;
  h5: Record<string, string>;
  body: Record<string, string>;
  caption: Record<string, string>;
}

@customElement('a2ui-text')
export class Text extends Root {
  @property()
  accessor text: Primitives.StringValue | null = null;

  @property({reflect: true, attribute: 'usage-hint'})
  accessor usageHint: Types.ResolvedText['usageHint'] | null = null;

  // Allow users to specify their own markdown renderer,
  // or the one provided by @a2ui/markdown-it.
  @consume({context: Context.markdown})
  accessor markdownRenderer: Types.MarkdownRenderer | undefined = undefined;

  static styles = [
    structuralStyles,
    css`
      :host {
        display: block;
        flex: var(--weight);
      }

      h1,
      h2,
      h3,
      h4,
      h5 {
        line-height: inherit;
        font: inherit;
      }
    `,
  ];

  #renderText() {
    let textValue: string | null | undefined = null;

    if (this.text && typeof this.text === 'object') {
      if ('literalString' in this.text && this.text.literalString) {
        textValue = this.text.literalString;
      } else if ('literal' in this.text && this.text.literal !== undefined) {
        textValue = this.text.literal;
      } else if (this.text && 'path' in this.text && this.text.path) {
        if (!this.processor || !this.component) {
          return html`(no model)`;
        }

        const value = this.processor.getData(
          this.component,
          this.text.path,
          this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID,
        );

        if (value !== null && value !== undefined) {
          textValue = value.toString();
        }
      }
    }

    if (textValue === null || textValue === undefined) {
      return html`(empty)`;
    }

    let markdownText = textValue;
    switch (this.usageHint) {
      case 'h1':
        markdownText = `# ${markdownText}`;
        break;
      case 'h2':
        markdownText = `## ${markdownText}`;
        break;
      case 'h3':
        markdownText = `### ${markdownText}`;
        break;
      case 'h4':
        markdownText = `#### ${markdownText}`;
        break;
      case 'h5':
        markdownText = `##### ${markdownText}`;
        break;
      case 'caption':
        markdownText = `*${markdownText}*`;
        break;
      default:
        break; // Body.
    }

    return html`${markdown(markdownText, this.markdownRenderer, {
      tagClassMap: Styles.appendToAll(this.theme.markdown, ['ol', 'ul', 'li'], {}),
    })}`;
  }

  #areHintedStyles(styles: unknown): styles is HintedStyles {
    if (typeof styles !== 'object') return false;
    if (Array.isArray(styles)) return false;
    if (!styles) return false;

    const expected = ['h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'caption', 'body'];
    return expected.every(v => v in styles);
  }

  #getAdditionalStyles() {
    let additionalStyles: Record<string, string> = {};
    const styles = this.theme.additionalStyles?.Text;
    if (!styles) return additionalStyles;

    if (this.#areHintedStyles(styles)) {
      const hint = this.usageHint ?? 'body';
      additionalStyles = styles[hint] as Record<string, string>;
    } else {
      additionalStyles = styles;
    }

    return additionalStyles;
  }

  render() {
    const classes = Styles.merge(
      this.theme.components.Text.all,
      this.usageHint ? this.theme.components.Text[this.usageHint] : {},
    );

    return html`<section
      class=${classMap(classes)}
      style=${this.theme.additionalStyles?.Text ? styleMap(this.#getAdditionalStyles()) : nothing}
    >
      ${this.#renderText()}
    </section>`;
  }
}

// renderers/react/src/v0_8/components/content/Text.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useMemo, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject, mergeClassMaps} from '../../lib/utils';
import MarkdownIt from 'markdown-it';

type UsageHint = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'caption' | 'body';

interface HintedStyles {
  h1?: Record<string, string>;
  h2?: Record<string, string>;
  h3?: Record<string, string>;
  h4?: Record<string, string>;
  h5?: Record<string, string>;
  body?: Record<string, string>;
  caption?: Record<string, string>;
}

function isHintedStyles(styles: unknown): styles is HintedStyles {
  if (typeof styles !== 'object' || !styles || Array.isArray(styles)) return false;
  const expected = ['h1', 'h2', 'h3', 'h4', 'h5', 'caption', 'body'];
  return expected.some(v => v in styles);
}

/**
 * Markdown-it instance for rendering markdown text.
 * Uses synchronous import to ensure availability at first render (matches Lit renderer).
 *
 * Configuration matches Lit's markdown directive (uses MarkdownIt defaults):
 * - html: false (default) - Security: disable raw HTML
 * - linkify: false (default) - Don't auto-convert URLs/emails to links
 * - breaks: false (default) - Don't convert \n to <br>
 * - typographer: false (default) - Don't use smart quotes/dashes
 */
const markdownRenderer = new MarkdownIt();

/**
 * Maps HTML tag names to their markdown-it token names.
 * Mirrors the Lit renderer's markdown directive approach.
 */
const TAG_TO_TOKEN: Record<string, string> = {
  p: 'paragraph',
  h1: 'heading',
  h2: 'heading',
  h3: 'heading',
  h4: 'heading',
  h5: 'heading',
  h6: 'heading',
  ul: 'bullet_list',
  ol: 'ordered_list',
  li: 'list_item',
  a: 'link',
  strong: 'strong',
  em: 'em',
};

function toClassArray(classes: string[] | Record<string, boolean>): string[] {
  if (Array.isArray(classes)) return classes;
  return Object.entries(classes)
    .filter(([, v]) => v)
    .map(([k]) => k);
}

/**
 * Render markdown to HTML, applying theme classes via markdown-it renderer rules.
 * Uses token.attrJoin() on _open tokens — same approach as the Lit renderer.
 * Safe to mutate the module-level renderer because MarkdownIt.render() is synchronous.
 */
function renderWithTheme(text: string, markdownTheme: Types.Theme['markdown']): string {
  const appliedKeys: string[] = [];
  // Cast to a generic record for dynamic token.tag lookups inside renderer rules
  const themeMap = markdownTheme as Record<string, string[] | Record<string, boolean>> | undefined;

  if (themeMap) {
    for (const [tag, classes] of Object.entries(themeMap)) {
      if (!classes) continue;
      const tokenName = TAG_TO_TOKEN[tag];
      if (!tokenName) continue;

      const key = `${tokenName}_open`;
      if (!appliedKeys.includes(key)) appliedKeys.push(key);

      markdownRenderer.renderer.rules[key] = (tokens, idx, options, _env, self) => {
        const token = tokens[idx];
        if (token) {
          const tagClasses = themeMap[token.tag];
          if (tagClasses) {
            for (const cls of toClassArray(tagClasses)) {
              token.attrJoin('class', cls);
            }
          }
        }
        return self.renderToken(tokens, idx, options);
      };
    }
  }

  const html = markdownRenderer.render(text);

  for (const key of appliedKeys) {
    delete markdownRenderer.renderer.rules[key];
  }

  return html;
}

/**
 * Text component - renders text content with markdown support.
 *
 * Structure mirrors Lit's Text component:
 *   <div class="a2ui-text">      ← :host equivalent
 *     <section class="...">      ← theme classes
 *       <h2>...</h2>             ← rendered markdown content
 *     </section>
 *   </div>
 *
 * Text is parsed as markdown and rendered as HTML (matches Lit renderer behavior).
 * Supports usageHint values: h1, h2, h3, h4, h5, caption, body
 *
 * Markdown features supported:
 * - **Bold** and *italic* text
 * - Lists (ordered and unordered)
 * - `inline code` and code blocks
 * - [Links](url) (auto-linkified URLs too)
 * - Blockquotes
 * - Horizontal rules
 *
 * Note: Raw HTML is disabled for security.
 */
export const Text = memo(function Text({node, surfaceId}: A2UIComponentProps<Types.TextNode>) {
  const {theme, resolveString} = useA2UIComponent(node, surfaceId);
  const props = node.properties;

  const textValue = resolveString(props.text);
  const usageHint = props.usageHint as UsageHint | undefined;

  // Get merged classes (matches Lit's Styles.merge)
  const classes = mergeClassMaps(
    theme.components.Text.all,
    usageHint ? theme.components.Text[usageHint] : {},
  );

  // Get additional styles based on usage hint
  const additionalStyles = useMemo(() => {
    const textStyles = theme.additionalStyles?.Text;
    if (!textStyles) return undefined;

    if (isHintedStyles(textStyles)) {
      const hint = usageHint ?? 'body';
      return stylesToObject(textStyles[hint]);
    }
    return stylesToObject(textStyles as Record<string, string>);
  }, [theme.additionalStyles?.Text, usageHint]);

  // Render markdown content (matches Lit behavior - always uses markdown)
  const renderedContent = useMemo(() => {
    if (textValue === null || textValue === undefined) {
      return null;
    }

    // Add markdown prefix based on usageHint (matches Lit behavior)
    let markdownText = textValue;
    switch (usageHint) {
      case 'h1':
        markdownText = `# ${markdownText}`;
        break;
      case 'h2':
        markdownText = `## ${markdownText}`;
        break;
      case 'h3':
        markdownText = `### ${markdownText}`;
        break;
      case 'h4':
        markdownText = `#### ${markdownText}`;
        break;
      case 'h5':
        markdownText = `##### ${markdownText}`;
        break;
      case 'caption':
        markdownText = `*${markdownText}*`;
        break;
      default:
        break; // Body - no prefix
    }

    return {__html: renderWithTheme(markdownText, theme.markdown)};
  }, [textValue, theme.markdown, usageHint]);

  if (!renderedContent) {
    return null;
  }

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-text" style={hostStyle}>
      <section
        className={classMapToString(classes)}
        style={additionalStyles}
        dangerouslySetInnerHTML={renderedContent}
      />
    </div>
  );
});

export default Text;
