// renderers/lit/src/0.8/ui/slider.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {Root} from './root.js';
import {A2uiMessageProcessor} from '@a2ui/web_core/data/model-processor';
import * as Primitives from '@a2ui/web_core/types/primitives';
import * as Types from '@a2ui/web_core/types/types';
import {classMap} from 'lit/directives/class-map.js';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';
import {extractNumberValue, extractStringValue} from './utils/utils.js';

@customElement('a2ui-slider')
export class Slider extends Root {
  @property()
  accessor value: Primitives.NumberValue | null = null;

  @property()
  accessor minValue = 0;

  @property()
  accessor maxValue = 0;

  @property()
  accessor label: Primitives.StringValue | null = null;

  static styles = [
    structuralStyles,
    css`
      * {
        box-sizing: border-box;
      }

      :host {
        display: block;
        flex: var(--weight);
      }

      input {
        display: block;
        width: 100%;
      }

      .description {
      }
    `,
  ];

  #setBoundValue(value: string) {
    if (!this.value || !this.processor) {
      return;
    }

    if (!('path' in this.value)) {
      return;
    }

    if (!this.value.path) {
      return;
    }

    this.processor.setData(
      this.component,
      this.value.path,
      value,
      this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID,
    );
  }

  #renderField(value: string | number) {
    return html`<section class=${classMap(this.theme.components.Slider.container)}>
      ${this.label
        ? html`<label class=${classMap(this.theme.components.Slider.label)} for="data">
            ${extractStringValue(this.label, this.component, this.processor, this.surfaceId)}
          </label>`
        : nothing}
      <input
        autocomplete="off"
        class=${classMap(this.theme.components.Slider.element)}
        style=${this.theme.additionalStyles?.Slider
          ? styleMap(this.theme.additionalStyles?.Slider)
          : nothing}
        @input=${(evt: Event) => {
          if (!(evt.target instanceof HTMLInputElement)) {
            return;
          }

          this.#setBoundValue(evt.target.value);
        }}
        id="data"
        name="data"
        .value=${value}
        type="range"
        min=${this.minValue ?? '0'}
        max=${this.maxValue ?? '0'}
      />
      <span class=${classMap(this.theme.components.Slider.label)}
        >${this.value
          ? extractNumberValue(this.value, this.component, this.processor, this.surfaceId)
          : '0'}</span
      >
    </section>`;
  }

  render() {
    if (this.value && typeof this.value === 'object') {
      if ('literalNumber' in this.value && this.value.literalNumber) {
        return this.#renderField(this.value.literalNumber);
      } else if ('literal' in this.value && this.value.literal !== undefined) {
        return this.#renderField(this.value.literal);
      } else if (this.value && 'path' in this.value && this.value.path) {
        if (!this.processor || !this.component) {
          return html`(no processor)`;
        }

        const textValue = this.processor.getData(
          this.component,
          this.value.path,
          this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID,
        );

        if (textValue === null) {
          return html`Invalid value`;
        }

        if (typeof textValue !== 'string' && typeof textValue !== 'number') {
          return html`Invalid value`;
        }

        return this.#renderField(textValue);
      }
    }

    return nothing;
  }
}

// renderers/react/src/v0_8/components/interactive/Slider.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, useCallback, useEffect, useId, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject} from '../../lib/utils';

/**
 * Slider component - a numeric value selector with a range.
 *
 * Supports two-way data binding for the value.
 */
export const Slider = memo(function Slider({
  node,
  surfaceId,
}: A2UIComponentProps<Types.SliderNode>) {
  const {theme, resolveNumber, resolveString, setValue, getValue} = useA2UIComponent(
    node,
    surfaceId,
  );
  const props = node.properties;
  const id = useId();

  const valuePath = props.value?.path;
  const initialValue = resolveNumber(props.value) ?? 0;
  // Match Lit's default values (minValue=0, maxValue=0)
  const minValue = props.minValue ?? 0;
  const maxValue = props.maxValue ?? 0;

  const [value, setLocalValue] = useState(initialValue);

  // Sync with external data model changes (path binding)
  useEffect(() => {
    if (valuePath) {
      const externalValue = getValue(valuePath);
      if (externalValue !== null && Number(externalValue) !== value) {
        setLocalValue(Number(externalValue));
      }
    }
  }, [valuePath, getValue]); // eslint-disable-line react-hooks/exhaustive-deps

  // Sync when literal value changes from props (server-driven updates via surfaceUpdate)
  useEffect(() => {
    if (props.value?.literalNumber !== undefined) {
      setLocalValue(props.value.literalNumber);
    }
  }, [props.value?.literalNumber]);

  const handleChange = useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      const newValue = Number(e.target.value);
      setLocalValue(newValue);

      // Two-way binding: update data model
      if (valuePath) {
        setValue(valuePath, newValue);
      }
    },
    [valuePath, setValue],
  );

  // Access label from props if it exists (Lit component supports it but type doesn't define it)
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const labelValue = (props as any).label;
  const label = labelValue ? resolveString(labelValue) : '';

  // Structure mirrors Lit's Slider component:
  //   <div class="a2ui-slider">    ← :host equivalent
  //     <section class="...">      ← internal element
  //       <label>...</label>
  //       <input>...</input>
  //       <span>value</span>
  //     </section>
  //   </div>

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-slider" style={hostStyle}>
      <section className={classMapToString(theme.components.Slider.container)}>
        {label && (
          <label htmlFor={id} className={classMapToString(theme.components.Slider.label)}>
            {label}
          </label>
        )}
        <input
          type="range"
          id={id}
          name="data"
          value={value}
          min={minValue}
          max={maxValue}
          onChange={handleChange}
          className={classMapToString(theme.components.Slider.element)}
          style={stylesToObject(theme.additionalStyles?.Slider)}
        />
        <span className={classMapToString(theme.components.Slider.label)}>{value}</span>
      </section>
    </div>
  );
});

export default Slider;
