// renderers/react/src/v0_8/components/layout/Tabs.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject, mergeClassMaps} from '../../lib/utils';
import {ComponentNode} from '../../core/ComponentNode';

/**
 * Tabs component - displays content in switchable tabs.
 */
export const Tabs = memo(function Tabs({node, surfaceId}: A2UIComponentProps<Types.TabsNode>) {
  const {theme, resolveString} = useA2UIComponent(node, surfaceId);
  const props = node.properties;

  const [selectedIndex, setSelectedIndex] = useState(0);

  const tabItems = props.tabItems ?? [];

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-tabs" style={hostStyle}>
      <section
        className={classMapToString(theme.components.Tabs.container)}
        style={stylesToObject(theme.additionalStyles?.Tabs)}
      >
        {/* Tab buttons - uses Tabs.element for the container */}
        <div id="buttons" className={classMapToString(theme.components.Tabs.element)}>
          {tabItems.map((tab, index) => {
            const title = resolveString(tab.title);
            const isSelected = index === selectedIndex;

            // Lit merges all + selected classes when selected
            const classes = isSelected
              ? mergeClassMaps(
                  theme.components.Tabs.controls.all,
                  theme.components.Tabs.controls.selected,
                )
              : theme.components.Tabs.controls.all;

            return (
              <button
                key={index}
                disabled={isSelected}
                className={classMapToString(classes)}
                onClick={() => setSelectedIndex(index)}
              >
                {title}
              </button>
            );
          })}
        </div>

        {/* Tab content */}
        {tabItems[selectedIndex] && (
          <ComponentNode node={tabItems[selectedIndex].child} surfaceId={surfaceId} />
        )}
      </section>
    </div>
  );
});

export default Tabs;

// renderers/lit/src/0.8/ui/tabs.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {html, css, PropertyValues, nothing} from 'lit';
import {customElement, property} from 'lit/decorators.js';
import {Root} from './root.js';
import {repeat} from 'lit/directives/repeat.js';
import {A2uiMessageProcessor} from '@a2ui/web_core/data/model-processor';
import * as Primitives from '@a2ui/web_core/types/primitives';
import {classMap} from 'lit/directives/class-map.js';
import {styleMap} from 'lit/directives/style-map.js';
import {structuralStyles} from './styles.js';
import {Styles} from '../index.js';

@customElement('a2ui-tabs')
export class Tabs extends Root {
  @property()
  accessor titles: Primitives.StringValue[] | null = null;

  @property()
  accessor selected = 0;

  static styles = [
    structuralStyles,
    css`
      :host {
        display: block;
        flex: var(--weight);
      }
    `,
  ];

  protected willUpdate(changedProperties: PropertyValues<this>): void {
    super.willUpdate(changedProperties);

    if (changedProperties.has('selected')) {
      for (const child of this.children) {
        child.removeAttribute('slot');
      }
      const selectedChild = this.children[this.selected];
      if (!selectedChild) {
        return;
      }

      selectedChild.slot = 'current';
    }
  }

  #renderTabs() {
    if (!this.titles) {
      return nothing;
    }

    return html`<div id="buttons" class=${classMap(this.theme.components.Tabs.element)}>
      ${repeat(this.titles, (title, idx) => {
        let titleString = '';
        if ('literalString' in title && title.literalString) {
          titleString = title.literalString;
        } else if ('literal' in title && title.literal !== undefined) {
          titleString = title.literal;
        } else if (title && 'path' in title && title.path) {
          if (!this.processor || !this.component) {
            return html`(no model)`;
          }

          const textValue = this.processor.getData(
            this.component,
            title.path,
            this.surfaceId ?? A2uiMessageProcessor.DEFAULT_SURFACE_ID,
          );

          if (typeof textValue !== 'string') {
            return html`(invalid)`;
          }

          titleString = textValue;
        }

        let classes;
        if (this.selected === idx) {
          classes = Styles.merge(
            this.theme.components.Tabs.controls.all,
            this.theme.components.Tabs.controls.selected,
          );
        } else {
          classes = {...this.theme.components.Tabs.controls.all};
        }

        return html`<button
          ?disabled=${this.selected === idx}
          class=${classMap(classes)}
          @click=${() => {
            this.selected = idx;
          }}
        >
          ${titleString}
        </button>`;
      })}
    </div>`;
  }

  #renderSlot() {
    return html`<slot name="current"></slot>`;
  }

  render() {
    return html`<section
      class=${classMap(this.theme.components.Tabs.container)}
      style=${this.theme.additionalStyles?.Tabs
        ? styleMap(this.theme.additionalStyles?.Tabs)
        : nothing}
    >
      ${[this.#renderTabs(), this.#renderSlot()]}
    </section>`;
  }
}
