// renderers/angular/src/v0_9/core/utils.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {DestroyRef, Signal, signal as angularSignal} from '@angular/core';
import {Signal as PreactSignal, effect, signal as preactSignal} from '@a2ui/web_core/v0_9';
export {preactSignal};

/**
 * Bridges a Preact Signal (from A2UI web_core) to a reactive Angular Signal.
 *
 * This utility handles the lifecycle mapping between Preact and Angular,
 * ensuring that updates from the A2UI data model are propagated correctly
 * to Angular's change detection, and resources are cleaned up when the
 * component is destroyed.
 *
 * @param preactSignal The source Preact Signal.
 * @param destroyRef Angular DestroyRef for lifecycle management.
 * @param ngZone Optional NgZone to ensure updates run within the Angular zone
 *               (necessary for correct change detection in OnPush components).
 * @returns A read-only Angular Signal.
 */
import {NgZone} from '@angular/core';

export function toAngularSignal<T>(
  preactSignal: PreactSignal<T>,
  destroyRef: DestroyRef,
  ngZone?: NgZone,
): Signal<T> {
  const s = angularSignal(preactSignal.peek());

  const dispose = effect(() => {
    if (ngZone) {
      ngZone.run(() => s.set(preactSignal.value));
    } else {
      s.set(preactSignal.value);
    }
  });

  destroyRef.onDestroy(() => {
    dispose();
    // Some signals returned by DataContext.resolveSignal have a custom unsubscribe for AbortControllers
    if ((preactSignal as any).unsubscribe) {
      (preactSignal as any).unsubscribe();
    }
  });

  return s.asReadonly();
}

/**
 * Normalizes a data model path by combining a relative path with a base context.
 *
 * This is used to create unique absolute paths for components within a repeating
 * collection or nested structure.
 *
 * @param path The relative or absolute path from the component properties.
 * @param dataContextPath The current base data context path.
 * @param index The index of the child component.
 * @returns A fully normalized absolute path for the indexed child.
 */
export function getNormalizedPath(
  path: string | undefined,
  dataContextPath: string,
  index: number,
): string {
  let normalized = path || '';
  if (!normalized.startsWith('/')) {
    const base = dataContextPath === '/' ? '' : dataContextPath;
    normalized = `${base}/${normalized}`;
  }
  if (normalized.endsWith('/')) {
    normalized = normalized.slice(0, -1);
  }
  return `${normalized}/${index}`;
}

// renderers/react/src/v0_8/theme/utils.ts
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Converts a theme class map (Record<string, boolean>) to a className string.
 *
 * @param classMap - An object where keys are class names and values are booleans
 * @returns A space-separated string of class names where the value is true
 *
 * @example
 * classMapToString({ 'a2ui-button': true, 'a2ui-button--primary': true, 'disabled': false })
 * // Returns: 'a2ui-button a2ui-button--primary'
 */
export function classMapToString(classMap: Record<string, boolean> | undefined): string {
  if (!classMap) return '';
  return Object.entries(classMap)
    .filter(([, enabled]) => enabled)
    .map(([className]) => className)
    .join(' ');
}

/**
 * Converts an additional styles object (Record<string, string>) to a React style object.
 *
 * @param styles - An object with CSS property names as keys and values as strings
 * @returns A React-compatible style object, or undefined if no styles
 *
 * @example
 * stylesToObject({ 'background-color': 'red', 'font-size': '16px', '--custom-var': 'blue' })
 * // Returns: { backgroundColor: 'red', fontSize: '16px', '--custom-var': 'blue' }
 */
export function stylesToObject(
  styles: Record<string, string> | undefined,
): React.CSSProperties | undefined {
  if (!styles || Object.keys(styles).length === 0) return undefined;

  const result: Record<string, string> = {};
  for (const [key, value] of Object.entries(styles)) {
    // Preserve CSS custom properties (--var-name) as-is
    if (key.startsWith('--')) {
      result[key] = value;
    } else {
      // Convert kebab-case to camelCase for React
      const camelKey = key.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
      result[camelKey] = value;
    }
  }
  return result as React.CSSProperties;
}
