// renderers/react/src/v0_8/components/layout/Tabs.tsx
/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {useState, memo} from 'react';
import type * as Types from '@a2ui/web_core/types/types';
import type {A2UIComponentProps} from '../../types';
import {useA2UIComponent} from '../../hooks/useA2UIComponent';
import {classMapToString, stylesToObject, mergeClassMaps} from '../../lib/utils';
import {ComponentNode} from '../../core/ComponentNode';

/**
 * Tabs component - displays content in switchable tabs.
 */
export const Tabs = memo(function Tabs({node, surfaceId}: A2UIComponentProps<Types.TabsNode>) {
  const {theme, resolveString} = useA2UIComponent(node, surfaceId);
  const props = node.properties;

  const [selectedIndex, setSelectedIndex] = useState(0);

  const tabItems = props.tabItems ?? [];

  // Apply --weight CSS variable on root div (:host equivalent) for flex layouts
  const hostStyle: React.CSSProperties =
    node.weight !== undefined ? ({'--weight': node.weight} as React.CSSProperties) : {};

  return (
    <div className="a2ui-tabs" style={hostStyle}>
      <section
        className={classMapToString(theme.components.Tabs.container)}
        style={stylesToObject(theme.additionalStyles?.Tabs)}
      >
        {/* Tab buttons - uses Tabs.element for the container */}
        <div id="buttons" className={classMapToString(theme.components.Tabs.element)}>
          {tabItems.map((tab, index) => {
            const title = resolveString(tab.title);
            const isSelected = index === selectedIndex;

            // Lit merges all + selected classes when selected
            const classes = isSelected
              ? mergeClassMaps(
                  theme.components.Tabs.controls.all,
                  theme.components.Tabs.controls.selected,
                )
              : theme.components.Tabs.controls.all;

            return (
              <button
                key={index}
                disabled={isSelected}
                className={classMapToString(classes)}
                onClick={() => setSelectedIndex(index)}
              >
                {title}
              </button>
            );
          })}
        </div>

        {/* Tab content */}
        {tabItems[selectedIndex] && (
          <ComponentNode node={tabItems[selectedIndex].child} surfaceId={surfaceId} />
        )}
      </section>
    </div>
  );
});

export default Tabs;

// renderers/angular/src/v0_8/components/tabs.ts
/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {ChangeDetectionStrategy, Component, input, signal} from '@angular/core';
import {DynamicComponent} from '../rendering/dynamic-component';
import {Renderer} from '../rendering/renderer';
import type {ResolvedTabs, TabsNode} from '../types';

@Component({
  selector: 'a2ui-tabs',
  imports: [Renderer],
  template: `
    <div [class]="theme.components.Tabs.container" [style]="theme.additionalStyles?.Tabs">
      <div [class]="theme.components.Tabs.controls.all">
        @for (item of tabItems(); track item.child; let i = $index) {
          <button
            [class]="selectedIndex() === i ? theme.components.Tabs.controls.selected : {}"
            (click)="selectTab(i)"
          >
            {{ resolvePrimitive(item.title) }}
          </button>
        }
      </div>
      <div class="a2ui-tabs-content">
        @if (tabItems()[selectedIndex()]; as selectedTab) {
          <ng-container a2ui-renderer [surfaceId]="surfaceId()!" [component]="selectedTab.child" />
        }
      </div>
    </div>
  `,
  styles: `
    :host {
      display: block;
    }
    .a2ui-tabs-content {
      flex: 1;
      min-height: 0;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Tabs extends DynamicComponent<TabsNode> {
  readonly tabItems = input.required<ResolvedTabs['tabItems']>();
  protected readonly selectedIndex = signal(0);

  protected selectTab(index: number) {
    this.selectedIndex.set(index);
  }
}
